### ISSUE TITLE
InfluxDB returned error: error reading influxDB

### ISSUE THREAD

**Issue by sorcer1122** [notrustverify/status#1]
Hi, would you mind posting settings for InfluxDB? Cannot hook it to Grafana

![Capture](https://github.com/notrustverify/status/assets/15838362/1e007883-37c9-463d-865d-3577ae38dddd)

Thanks

**Comment by sorcer1122** [comment]
Anyone?

**Comment by sven-hash** [comment]
Hi, the settings are basic, just a bucket with read-write

**Comment by sorcer1122** [comment]
Finally managed to access InfluxDB, now getting this while dashboard is starting

`invalid parameter "match[]": 1:8: parse error: unexpected string "\"influxdat"...
`

Not sure how to fix it, would appreciate any help.

**Comment by sven-hash** [comment]
Seems like to be influx configuration

Will close the issue
